In [ ]:
import pandas as pd


data = pd.read_csv('/content/student-por.csv', delimiter=';')

data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
data.head() # By default, shows first 5 rows

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
data.tail()  # Shows last 5 rows

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [ ]:
# View random rows from the dataset
data.sample(5)# Random sample of 5 rows

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
560,MS,M,17,R,GT3,T,1,1,other,services,...,4,5,5,1,3,2,0,10,9,10
536,MS,M,15,U,LE3,A,2,2,other,other,...,5,4,5,2,3,5,8,13,14,14
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
392,GP,F,17,U,GT3,T,3,2,other,other,...,4,3,2,2,3,2,0,12,13,15
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,4,12,11,12

In [ ]:
# Get the shape (rows, columns)
data.shape

(649, 33)

In [ ]:
# Get the column names
data.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [ ]:
# Get data types of each column
data.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [ ]:

# Get general information about the DataFrame (memory usage, non-null counts, etc.)
print(data.info())

# Get summary statistics for numerical columns
print(data.describe())

# Get summary statistics for all columns (including categorical)
print(data.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB
None
              age        Medu        Fedu  traveltime   studytime    failures  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000
mean    16.744222    2.514638    2.306626    1.568567    1.930663    0.221880
std      1.218138    1.134552    1.099931    0.748660    0.829510    0.593235
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000
25%     16.000000    2.000000    1.000000    1.000000    1.000000    0.000000
50%     17.000000    2.000000    2.000000    1.000000    2.000000    0.000000
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000

           famrel    freetime       goout        Dalc        Walc      health  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000
mean     3.930663    3.180277    3.184900    1.502311    2.280431    3.536210
std      0.955717    1.051093    1.175766    0.924834    1.284380    1.446259
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

         absences          G1          G2          G3
count  649.000000  649.000000  649.000000  649.000000
mean     3.659476   11.399076   11.570108   11.906009
std      4.640759    2.745265    2.913639    3.230656
min      0.000000    0.000000    0.000000    0.000000
25%      0.000000   10.000000   10.000000   10.000000
50%      2.000000   11.000000   11.000000   12.000000
75%      6.000000   13.000000   13.000000   14.000000
max     32.000000   19.000000   19.000000   19.000000
       school  sex         age address famsize Pstatus        Medu  \
count     649  649  649.000000     649     649     649  649.000000
unique      2    2         NaN       2       2       2         NaN
top        GP    F         NaN       U     GT3       T         NaN
freq      423  383         NaN     452     457     569         NaN
mean      NaN  NaN   16.744222     NaN     NaN     NaN    2.514638
std       NaN  NaN    1.218138     NaN     NaN     NaN    1.134552
min       NaN  NaN   15.000000     NaN     NaN     NaN    0.000000
25%       NaN  NaN   16.000000     NaN     NaN     NaN    2.000000
50%       NaN  NaN   17.000000     NaN     NaN     NaN    2.000000
75%       NaN  NaN   18.000000     NaN     NaN     NaN    4.000000
max       NaN  NaN   22.000000     NaN     NaN     NaN    4.000000

              Fedu   Mjob   Fjob  ...      famrel    freetime       goout  \
count   649.000000    649    649  ...  649.000000  649.000000  649.000000
unique         NaN      5      5  ...         NaN         NaN         NaN
top            NaN  other  other  ...         NaN         NaN         NaN
freq           NaN    258    367  ...         NaN         NaN         NaN
mean      2.306626    NaN    NaN  ...    3.930663    3.180277    3.184900
std       1.099931    NaN    NaN  ...    0.955717    1.051093    1.175766
min       0.000000    NaN    NaN  ...    1.000000    1.000000    1.000000
25%       1.000000    NaN    NaN  ...    4.000000    3.000000    2.000000
50%       2.000000    NaN    NaN  ...    4.000000    3.000000    3.000000
75%       3.000000    NaN    NaN  ...    5.000000    4.000000    4.000000
max       4.000000    NaN    NaN  ...    5.000000    5.000000    5.000000

              Dalc        Walc      health    absences          G1  \
count   649.000000  649.000000  649.000000  649.000000  649.000000
unique         NaN         NaN         NaN         NaN         NaN
top            NaN         NaN         NaN         NaN         NaN
freq           NaN         NaN         NaN         NaN         NaN
mean      1.502311    2.280431    3.536210    3.659476   11.399076
std       0.924834    1.284380    1.446259    4.640759    2.745265
min       1.000000    1.000000    1.000000    0.000000    0.000000
25%       1.000000    1.000000    2.000000    0.000000   10.000000
50%       1.000000    2.000000    4.000000    2.000000   11.000000
75%       2.000000    3.000000    5.000000    6.000000   13.000000
max       5.000000    5.000000    5.000000   32.000000   19.000000

                G2          G3
count   649.000000  649.000000
unique         NaN         NaN
top            NaN         NaN
freq           NaN         NaN
mean     11.570108   11.906009
std       2.913639    3.230656
min       0.000000    0.000000
25%      10.000000   10.000000
50%      11.000000   12.000000
75%      13.000000   14.000000
max      19.000000   19.000000

[11 rows x 33 columns]